shop/apps/accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/', VerifyRegisterCreateView.as_view(), name='verify'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('userpanel/', UserPanelView.as_view(), name='userpanel'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('remember_password/', RememberPasswordView.as_view(), name='remember_password'),
    
    path('userpanel/', UserPanelView.as_view(), name='userpanel'),
    path('show_last_order/', show_last_order, name='show_last_order'),
    path('update_profile/', UpdateProfile.as_view(), name='update_profile'),
    path('show_user_payments/', show_user_payments, name='show_user_payments'),
]

shop/apps/comment_scoring_favorites/urls.py
from django.urls import path
from . import views


app_name = 'csf'
urlpatterns = [
    path('create_comment/<slug:slug>/', views.CommentView.as_view(), name='create_comment'),
    path('add_score/', views.add_score, name='add_score'),
    path('add_to_favorite/', views.add_to_favorite, name='add_to_favorite'),
    path('user_favorite/', views.UserFavorite.as_view(), name='user_favorite'),

    path('delete_favorite/', views.delete_favorite, name='delete_favorite'),
    path('show_wishlist/', views.show_wishlist, name='show_wishlist'),
    
    
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('discounts/', include('apps.discounts.urls', namespace='discounts')),
    path('payments/', include('apps.payments.urls', namespace='payments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    path('csf/', include('apps.comment_scoring_favorites.urls', namespace='csf')),
    path('search/', include('apps.search.urls', namespace='seach')),
    path('test_api/', include('apps.test_api.urls', namespace='test_api')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

shop/templates/csf_app/partials/create_comment.html
<form action="{% url 'csf:create_comment' slug=slug %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label class="review-text">دیدگاه شما</label>
        {{ form.as_p }}
    </div>
    <div class="form-group md-0">
        <button type="submit" class="btn btn-primary btn-lg">ارسال نظر</button>
    </div>
</form>

shop/templates/csf_app/partials/score.html
{% comment %} 
<div style="display: flex; justify-content: space-between;">
									
    <h6>میانگین امتیاز کالا :<span style="color: red;">{{product.get_average_score}}</span></h6>
    {% if user.is_authenticated %}
        {% if product.get_user_score > 0 %}
            <div>
                {% with ''|center:5 as range %}
                    {% for i in range %}
                        {% if forloop.counter <= product.get_user_score %}
                            <span id="star_{{ forloop.counter }}" class="fa fa-star checked"></span> 
                        {% else %}
                            <span id="star_{{ forloop.counter }}" class="fa fa-star"></span>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </div>
        {% else %}
            <div>
                <span id="star_1" class="fa fa-star cursor-pointer" onclick="addScore(1, {{product.id}})"></span> 
                <span id="star_2" class="fa fa-star cursor-pointer" onclick="addScore (2, {{product.id}})"></span> 
                <span id="star_3" class="fa fa-star cursor-pointer" onclick="addScore (3, {{product.id}})"></span> 
                <span id="star_4" class="fa fa-star cursor-pointer" onclick="addScore(4, {{product.id}})"></span> 
                <span id="star_5" class="fa fa-star cursor-pointer" onclick="addScore(5, {{product.id}})"></span> 
            </div>
        {% endif %}
    {% else %}
        <h6 style="text-decoration: underline;">
        برای امتیاز دهی
        <a href="{% url 'accounts: login' %}?next=/products/product_details/{{product.slug}}/"></a>
        با
        <a href="{% url 'accounts:register' %}?next=/products/product_details/{{product.slug}}/"></a>
        کنید
        </h6> 
    {% endif %}
</div> {% endcomment %}
{% comment %} </div> {% endcomment %}


<div id="score_refresh" style="display: flex; justify-content: space-between;">
									
    <h6>میانگین امتیاز کالا :<span  id="avg_score_{{product.id}}" style="color: red;">{{product.get_average_score}}</span></h6>
    {% if user.is_authenticated %}
        {% if product.get_user_score > 0 %}
            <div>
                {% with ''|center:5 as range %}
                    {% for i in range %}
                        {% if forloop.counter <= product.get_user_score %}
                            <span id="star_{{ forloop.counter }}" class="fa fa-star checked"></span> 
                        {% else %}
                            <span id="star_{{ forloop.counter }}" class="fa fa-star"></span>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </div>
        {% else %}
            <div>
                <span id="star_1" class="fa fa-star cursor-pointer" onclick="addScore(1, {{product.id}})"></span> 
                <span id="star_2" class="fa fa-star cursor-pointer" onclick="addScore(2, {{product.id}})"></span> 
                <span id="star_3" class="fa fa-star cursor-pointer" onclick="addScore(3, {{product.id}})"></span> 
                <span id="star_4" class="fa fa-star cursor-pointer" onclick="addScore(4, {{product.id}})"></span> 
                <span id="star_5" class="fa fa-star cursor-pointer" onclick="addScore(5, {{product.id}})"></span> 
            </div>
        {% endif %}
    {% else %}
        <h6 style="text-decoration: underline;">
        برای امتیاز دهی
        <a href="{% url 'accounts:login' %}?next=/products/product_details/{{product.slug}}/"></a>
        با
        <a href="{% url 'accounts:register' %}?next=/products/product_details/{{product.slug}}/"></a>
        کنید
        </h6> 
    {% endif %}
</div>
</div>

shop/templates/csf_app/partials/show_comments.html
{% load render_partial %}

<div class="product-tabs__pane" id="tab-reviews">
  <div class="reviews-view">
    <div class="reviews-view__list">
      <h3 class="reviews-view__header">دیدگاههای مشتریان</h3>
      <div class="reviews-list">
        <ol class="reviews-list__content">
          {% for comment in product.comments_product.all %}
            {% if comment.is_active %}
              {% if comment.comment_parent == None %}
                <li class="reviews-list__item" style="display: flex; justify-content: space-between;">
                  <div class="review">
                    <div class="review__avatar">
                      <img src="{{ media_url }}images/avatars/avatar-2.jpg" alt="" />
                    </div>
                    <div class="review__content">
                      <div class="review__author">{{ comment.commenting_user.name }}</div>
                      <div class="review__text">{{ comment.comment_text }}</div>
                      {% comment %} <div class="review__date">{{ comment.registerdate }}</div> {% endcomment %}
                    </div>
                  </div>
                  <div>
                    {% if user.is_authenticated %}
                      <div>
                        <a class="btn btn-info" id="btn_{{ comment.id }}" onclick="showCreateCommentForm({{ product.id }},{{ comment.id }},'{{ product.slug }}');">پاسخ</a>
                      </div>
                      <div id="comment_form_{{ comment.id }}"></div>
                    {% endif %}
                  </div>
                </li>
                {% for item in comment.comments_child.all %}
                  {% if item.is_active %}
                      <li class="reviews-list_item" style="background-color: beige; width: 95%; margin: 10px 5%;">
                        <div class="review">
                          <div class="review__avatar">
                            <img src="{{ media_url }}images/avatars/avatar-4.jpg" alt="" />
                          </div>
                          <div class="review_content">
                            <div class="review_author">{{ item.commenting_user.name }}</div>
                            <div class="review_text">{{ item.comment_text }}</div>
                            <div class="review__date">{{ item.registerdate }}</div>
                          </div>
                        </div>
                      </li>
                  {% endif %}
                {% endfor %}
              {% else %}

              {% endif %}
            {% endif %}
          {% endfor %}
        </ol>
      </div>
    </div>

    {% if user.is_authenticated %}
      <h3 class="reviews-view__header">دیدگاه های خو را بنویسید</h3>
      <div class="row">
        <div class="col-12 col-lg-9 col-xl-8">
          {% render_partial 'csf:create_comment' slug=product.slug %}
        </div>
      </div>
    {% else %}
      <h5>
        برای درج دیدگاه خود باید
        <a href="{% url 'accounts:login' %}?next=/products/{{ product.slug }}/">ورود</a>
        با
        <a href="{% url 'accounts:register' %}?next=/products/{{ product.slug }}/">ثبت نام</a>
        کنید
      </h5>
    {% endif %}
  </div>
</div>

shop/templates/csf_app/partials/show_wishlist.html
{% load humanize %}


<div class="page-header">
    <div class="page-header__container container">
        <div class="page-header__breadcrumb">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">خانه</a>
                        /
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">علاقه‌مندی‌ها</li>
                </ol>
            </nav>
        </div>
        <div class="page-header__title">
            <h1>علاقه‌مندی‌ها</h1></div>
    </div>
</div>
<div class="block">
    <div class="container">
        {% if user_favorite %}
            <table class="wishlist">
                <thead class="wishlist__head">
                    <tr class="wishlist__row">
                        <th class="wishlist__column wishlist__column--image">تصویر</th>
                        <th class="wishlist__column wishlist__column--product">محصول</th>
                        <th class="wishlist__column wishlist__column--stock">وضعیت انبار</th>
                        <th class="wishlist__column wishlist__column--price">قیمت</th>
                        <th class="wishlist__column wishlist__column--tocart"></th>
                        <th class="wishlist__column wishlist__column--remove"></th>
                    </tr>
                </thead>
                <tbody class="wishlist__body">
                    {% for favorite in user_favorite %}
                    <tr class="wishlist__row">
                        <td class="wishlist__column wishlist__column--image">
                            <a href=""><img src="{{media_url}}{{favorite.product.image_name}}" alt=""></a>
                        </td>
                        <td class="wishlist__column wishlist__column--product">
                            <a href="" class="wishlist__product-name">
                                {{favorite.product.product_name}}
                            </a>
                        </td>
                        <td class="wishlist__column wishlist__column--stock">
                            {% if favorite.product.get_number_in_warehouse > 0 %}
                                <div class="badge badge-success">موجود در انبار</div>
                            {% elif favorite.product.get_number_in_warehouse > 0 %}
                                <div class="badge badge-danger">ناموجود در انبار</div>
                            {% endif %}
                        </td>
                        <td class="wishlist__column wishlist__column--price">{{favorite.product.price| intcomma:False}} تومان</td>
                        <td class="wishlist__column wishlist__column--tocart">
                            <button type="button" class="btn btn-primary btn-sm" onclick="add_to_shop_cart({{favorite.product.id}},1)">افزودن به سبد</button>
                        </td>
                        <td class="wishlist__column wishlist__column--remove" onclick="deleteFromFavoriteList({{favorite.product.id}})">
                            <i class="fa fa-trash" style="cursor: pointer;">
                            </i>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% else %}
<h3>کالایی وجود ندارد</h3>
{% endif %}