shop/apps/accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/', VerifyRegisterCreateView.as_view(), name='verify'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('userpanel/', UserPanelView.as_view(), name='userpanel'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('remember_password/', RememberPasswordView.as_view(), name='remember_password'),
    
    path('userpanel/', UserPanelView.as_view(), name='userpanel'),
    path('show_last_order/', show_last_order, name='show_last_order'),
    path('update_profile/', UpdateProfile.as_view(), name='update_profile'),
    path('show_user_payments/', show_user_payments, name='show_user_payments'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('discounts/', include('apps.discounts.urls', namespace='discounts')),
    path('payments/', include('apps.payments.urls', namespace='payments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    path('csf/', include('apps.comment_scoring_favorites.urls', namespace='csf')),
    path('search/', include('apps.search.urls', namespace='seach')),
    path('test_api/', include('apps.test_api.urls', namespace='test_api')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>
    <link rel="icon" type="image/png" href="images/favicon.png">
	<!-- css -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %} ">
	<link rel="stylesheet" href="{% static 'css/style.css' %} ">
	<link rel="stylesheet" href="{% static 'css/custom.css' %} ">
	<!-- js -->
	<script src="{% static 'vendor/jquery-3.3.1/jquery.min.js' %} "></script>
	<script src="{% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %} "></script>
	<script src="{% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %} "></script>
	<script src="{% static 'js/main.js' %} "></script>
	<script src="{% static 'js/myscript.js' %} "></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href="{% static 'vendor/fontawesome-5.6.3/css/all.min.css' %} ">
</head>
<body>

	{% include "partials/header.html" %}
	{% include "partials/messages.html" %}
    {% block content %}{% endblock content %}
    {% include "partials/footer.html" %}



</body>
</html>

shop/templates/user_panel_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}پنل کاربری{% endblock title %}
    </title>
    <link rel="icon" type="image/png" href="images/favicon.png">
	<!-- css -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %} ">
	<link rel="stylesheet" href="{% static 'css/style.css' %} ">
	<link rel="stylesheet" href="{% static 'css/custom.css' %} ">
	<!-- js -->
	<script src="{% static 'vendor/jquery-3.3.1/jquery.min.js' %} "></script>
	<script src="{% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %} "></script>
	<script src="{% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %} "></script>
	<script src="{% static 'js/main.js' %} "></script>
	<script src="{% static 'js/myscript.js' %} "></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href="{% static 'vendor/fontawesome-5.6.3/css/all.min.css' %} ">
</head>
<body>

	{% include "partials/header.html" %}
	{% include "partials/messages.html" %}
    
    		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">

					<div class="page-header__title">
						<h1>حساب کاربری</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row">
						<div class="col-12 col-lg-3 d-flex">
							<div class="account-nav flex-grow-1">
								<h4 class="account-nav__title">منو اصلی</h4>
								<ul>
									<li class="account-nav__item account-nav__item--active"><a href="{% url 'accounts:userpanel' %}">داشبورد</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:update_profile' %}">ویرایش پروفایل</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:show_user_payments' %}">سابقه خرید</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:change_password' %}">تغییر رمز عبور</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">خروج</a></li>
								</ul>
							</div>
						</div>
						<div class="col-12 col-lg-9 mt-4 mt-lg-0">
                            {% block content %}{% endblock content %}

						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->

</body>
</html>