shop/apps/accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/', VerifyRegisterCreateView.as_view(), name='verify'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('userpanel/', UserPanelView.as_view(), name='userpanel'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('remember_password/', RememberPasswordView.as_view(), name='remember_password'),
    
    path('userpanel/', UserPanelView.as_view(), name='userpanel'),
    path('show_last_order/', show_last_order, name='show_last_order'),
    path('update_profile/', UpdateProfile.as_view(), name='update_profile'),
    path('show_user_payments/', show_user_payments, name='show_user_payments'),
]

shop/apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('shop_cart/', views.ShopCartView.as_view(), name='shop_cart'),
    path('show_shop_cart/', views.show_shop_cart, name='show_shop_cart'),
    path('add_to_shop_cart/', views.add_to_shop_cart, name='add_to_shop_cart'),
    path('delete_from_shop_cart/', views.delete_shop_cart, name='delete_from_shop_cart'),
    path('update_shop_cart/', views.update_shop_cart, name='update_shop_cart'),
    path('status_of_shop_cart/', views.status_of_shop_cart, name='status_of_shop_cart'),
    path('create_order/', views.CreateOrderView.as_view(), name='create_order'),
    path('checkout_order/<int:order_id>', views.CheckoutOrderView.as_view(), name='checkout_order'),
    path('applay_coupen/<int:order_id>/', views.ApplayCoupon.as_view(), name='applay_coupen')
]

shop/apps/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('cheapest_products/', views.get_cheapest_products, name='cheapest_products'),
    path('last_products/', views.get_last_products, name='last_products'),
    path('popular_product_groups/', views.get_popular_product_groups, name='popular_product_groups'),
    path('product_details/<slug:slug>/', views.ProductDetailView.as_view(), name='product_details'),
    path('related_products/<slug:slug>/', views.get_related_products, name='related_products'),
    path('product_groups/', views.ProductGroupsView.as_view(), name='product_groups'),
    path('products_of_group/<slug:slug>/', views.ProductByGroupView.as_view(), name='products_of_group'),
    path('ajax_admin/',  views.get_filter_value_for_feature, name='filter_value_for_feature'),
    path('product_groups_partial/get_product_groups',  views.get_product_groups, name='product_groups_partial'),
    path('brand_partial/<slug:slug>/',  views.get_brands, name='brand_partial'),
    path('features_for_filter/<slug:slug>/',  views.get_feature_for_filter, name='features_for_filter'),
    
    path('status_of_compare_list/',  views.status_of_compare_list, name='status_of_compare_list'),
    path('compare_list/',  views.ShowCompareListView.as_view(), name='compare_list'),
    path('compare_table/',  views.compare_table, name='compare_table'),
    path('add_to_compare_list/',  views.add_to_compare_list, name='add_to_compare_list'),
    path('delete_from_compare_list/',  views.delete_from_compare_list, name='delete_from_compare_list'),
    
    path('category/',  views.category, name='category'),
    path('products_groups/<slug:slug>/',  views.products_groups, name='products_groups'),
    path('products_parent_group/<slug:slug>/',  views.products_parent_group, name='products_parent_group'),
]

shop/apps/search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('', views.SearchResultsView.as_view(), name = 'search_results')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('discounts/', include('apps.discounts.urls', namespace='discounts')),
    path('payments/', include('apps.payments.urls', namespace='payments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    path('csf/', include('apps.comment_scoring_favorites.urls', namespace='csf')),
    path('search/', include('apps.search.urls', namespace='seach')),
    path('test_api/', include('apps.test_api.urls', namespace='test_api')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

shop/templates/partials/category.html
<li class="nav-links__item nav-links__item--with-submenu">
  <a href="product-categories.html">
    <span>
      دسته بندی کالاها
      &nbsp;
      <i class="fa fa-angle-down"></i>
    </span>
  </a>
  <div class="nav-links__megamenu nav-links__megamenu--size--lg">
    <!-- .megamenu -->
    <div class="megamenu">
      <div class="row">

        {% for group_parent in group_parents %}
          {% if group_parent.groups.all %}
          <div class="col-3">
            <ul class="megamenu__links megamenu__links--level--0">
              <li class="megamenu__item megamenu__item--with-submenu">
                <a href="{% url "products:products_parent_group" slug=group_parent.slug %}">{{group_parent}}</a>
                <ul class="megamenu__links megamenu__links--level--1">

                  {% for group in group_parent.groups.all %}
                    {% if group.products_of_groups.all %}
                      <li class="megamenu__item">
                        <a href="{% url "products:products_groups" slug=group.slug %}">{{group}}</a>
                      </li>
                    {% endif %}
                  {% endfor %}
               
                </ul>
              </li>
            </ul>
          </div>
          {% endif %}
        {% endfor %}

      </div>
    </div>
    <!-- .megamenu / end -->
  </div>
</li>

shop/templates/partials/footer.html
		<!-- site__footer -->
		<footer class="site__footer">
			<div class="site-footer">
				<div class="container">
					<div class="site-footer__widgets">
						<div class="row">
							<div class="col-12 col-md-6 col-lg-4">
								<div class="site-footer__widget footer-contacts">
									<h5 class="footer-contacts__title">تماس با ما</h5>

									<ul class="footer-contacts__contacts">
										<li><i class="footer-contacts__icon fas fa-globe-americas"></i>
											ملایر، خیابان شهدا</li>
										<li><i class="footer-contacts__icon fas fa-mobile-alt"></i>
											<span class="ltr_text">081-45231</span>
										</li>

									</ul>
								</div>
							</div>
							<div class="col-6 col-md-3 col-lg-2">
								<div class="site-footer__widget footer-links">
									<h5 class="footer-links__title">اطلاعات</h5>
									<ul class="footer-links__list">
										<li class="footer-links__item">
											<a href="" class="footer-links__link">درباره ما</a>
										</li>
										<li class="footer-links__item">
											<a href="" class="footer-links__link">تماس با ما</a>
										</li>
										<li class="footer-links__item">
											<a href="" class="footer-links__link">قوانین و مقررات</a>
										</li>
									</ul>
								</div>
							</div>
							<div class="col-6 col-md-3 col-lg-2">
								<div class="site-footer__widget footer-links">
									<h5 class="footer-links__title">حساب کاربری</h5>
									<ul class="footer-links__list">
										<li class="footer-links__item">
											<a href="login.html" class="footer-links__link">
												ورود
											</a>
										</li>
										<li class="footer-links__item">
											<a href="register.html" class="footer-links__link">
												ثبت نام
											</a>
										</li>
									</ul>
								</div>
							</div>
							<div class="col-12 col-md-12 col-lg-4">
								<div class="site-footer__widget footer-newsletter">
									<h5 class="footer-contacts__title">شبکه های</h5>
									<div class="footer-newsletter__text footer-newsletter__text--social">ما را در شبکه
										های اجتماعی دنبال کنید</div>
									<ul class="footer-newsletter__social-links">
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--facebook">
											<a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
										</li>
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--twitter">
											<a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
										</li>
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--youtube">
											<a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
										</li>
										<li
											class="footer-newsletter__social-link footer-newsletter__social-link--instagram">
											<a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
										</li>
										<li class="footer-newsletter__social-link footer-newsletter__social-link--rss">
											<a href="#" target="_blank"><i class="fas fa-rss"></i></a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="site-footer__bottom">

						<div class="site-footer__copyright">
							کلیه حقوق و امتیازات این وبسایت متعلق است به آکادمی
							<a href="https://darsman.com" target="_blank">درسمن</a>
						</div>

					</div>
				</div>
			</div>
		</footer>
		<!-- site__footer / end -->

shop/templates/partials/header.html
		<!-- desktop site__header -->
		<header class="site__header d-lg-block d-none">
			<div class="site-header">
				<!-- .topbar -->
				<div class="site-header__topbar topbar">
					<div class="topbar__container container">
						<div class="topbar__row">
							<div class="topbar__item topbar__item--link"><a class="topbar-link"
									href="about-us.html">درباره ما</a></div>
							<div class="topbar__item topbar__item--link"><a class="topbar-link"
									href="contact-us.html">تماس با ما</a></div>
							<div class="topbar__spring"></div>
							<div class="topbar__item">
								<div class="topbar-dropdown">

									{% if user.is_authenticated %}
									<button class="topbar-dropdown__btn" type="button">
										<a href="{% url 'accounts:userpanel' %}" class="topbar-link">پنل کاربری</a>
										<i class="fa fa-user"></i>
									</button>
									{% endif %}

								</div>
							</div>

						</div>
					</div>
				</div>

				<div class="site-header__middle container">
					<div class="site-header__logo">
						<a href="index.html">
							<img src="{{media_url}}/images/logo.png" alt="">
						</a>
					</div>
					<div class="site-header__search">
						<div class="search">
							<div>اعضای تیم: مریم زبرجد، احمد میرزایی، امیرحسین طاهری</div>
							{% comment %} <form class="search__form" action="">
								<input class="search__input" name="search" placeholder="جستجو از میان 10,000 محصول"
									aria-label="Site search" type="text" autocomplete="off">
								<button class="search__button" type="submit">
									<i class="fa fa-search"></i>
								</button>
								<div class="search__border"></div>
							</form> {% endcomment %}
						</div>
					</div>
					<div class="site-header__phone">
						<div class="site-header__phone-title">پشتیبانی</div>
						<div class="site-header__phone-number"><span class="ltr_text">081-45231</span></div>
					</div>
				</div>
				<!-- .topbar / end -->
				{% include "partials/navbar.html" %}
			</div>
		</header>
		<!-- desktop site__header / end -->

shop/templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <h1 class="alert alert-{{message.tags}}">
            {{message}}
        </h1>
    {% endfor %}
{% endif %}

shop/templates/partials/navbar.html
{% load render_partial %}

<div class="site-header__nav-panel">
  <div class="nav-panel">
    <div class="nav-panel__container container">
      <div class="nav-panel__row">
        <div class="nav-panel__logo">
          <a href="index.html"><img src="{{ media_url }}/images/shopLogo.png" alt="" /></a>
        </div>
        <!-- .nav-links -->
        <div class="nav-panel__nav-links nav-links">
          <ul class="nav-links__list">
            
            <li class="nav-links__item nav-links__item--with-submenu">
              <a href="/"><span><i class="fa fa-home"></i>&nbsp; خانه</span></a>
            </li>

            {% render_partial "products:category" %}

            <li class="nav-links__item nav-links__item--with-submenu">
              <a href="#"><span>حساب کاربری&nbsp;<i class="fa fa-angle-down"></i></span></a>
              <div class="nav-links__menu">
                <!-- .menu -->
                {% if user.is_authenticated %}
                <ul class="menu menu--layout--classic">
                    <li><a href="{% url "accounts:logout" %}">خروج</a></li>
                </ul>

                {% else %}
                <ul class="menu menu--layout--classic">
                  <li><a href="{% url "accounts:login" %}">ورود</a></li>
                  <li><a href="{% url 'accounts:register' %}">ثبت نام</a></li>
                </ul>

                {% endif %}

                <!-- .menu / end -->
              </div>
            </li>
            <li class="nav-links__item nav-links__item--with-submenu">
              <a href="blog.html"><span><i class="fa fa-newspaper"></i>&nbsp; بلاگ</span></a>
            </li>
          </ul>
        </div>
        <!-- .nav-links / end -->
        <div class="nav-panel__indicators">
          <div class="indicator indicator--trigger--click">
            <button type="button" class="indicator__button"><span class="indicator__area"><i class="fa fa-search"></i></span></button>
            <div class="indicator__dropdown">
              <div class="drop-search">

                <form action="{% url "search:search_results" %}" class="drop-search__form">
                  <input class="drop-search__input" name="q" placeholder="جستجو از میان 10,000 محصول" aria-label="Site search" type="text" autocomplete="off" />
                  <button class="drop-search__button drop-search__button--submit" type="submit"><i class="fa fa-search"></i></button>
                </form>
                
              </div>
            </div>
          </div>
          <div class="indicator">
            <a href="{% url "csf:user_favorite" %}" class="indicator__button">
              <span class="indicator__area">
                <i class="fa fa-heart"></i>
                <span class="indicator__value">0</span>
              </span>
            </a>
          </div>
          <div class="indicator">
            <a href="{% url "orders:shop_cart" %}" class="indicator__button">
              <span class="indicator__area">
                <i class="fa fa-shopping-cart"></i>
                <span class="indicator__value" id="indicator__value">0</span>
              </span>
            </a>
          </div>

          <div class="indicator" id="compare_count_icon">
            <a href="{% url "products:compare_list" %}" class="indicator__button">
              <span class="indicator__area">
                <i class="fa fa-play"></i>
                <span class="indicator__value" id="compare_count">0</span>
              </span>
            </a>
          </div>



          <div class="indicator" style="padding-right: 50px; display: flex;" >
            {% if user.name %}
            <a href="" class="indicator__button">{{user}}</a>
            <span class="indicator__area">
              <i class="fa fa-user-circle"></i>
              </span>

            {% else %}
            <a href="" class="indicator__button">{{user.mobile_number}}</a>
            <span class="indicator__area">
              <i class="fa fa-user-circle"></i>
              </span>

            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>