shop/apps/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('cheapest_products/', views.get_cheapest_products, name='cheapest_products'),
    path('last_products/', views.get_last_products, name='last_products'),
    path('popular_product_groups/', views.get_popular_product_groups, name='popular_product_groups'),
    path('product_details/<slug:slug>/', views.ProductDetailView.as_view(), name='product_details'),
    path('related_products/<slug:slug>/', views.get_related_products, name='related_products'),
    path('product_groups/', views.ProductGroupsView.as_view(), name='product_groups'),
    path('products_of_group/<slug:slug>/', views.ProductByGroupView.as_view(), name='products_of_group'),
    path('ajax_admin/',  views.get_filter_value_for_feature, name='filter_value_for_feature'),
    path('product_groups_partial/get_product_groups',  views.get_product_groups, name='product_groups_partial'),
    path('brand_partial/<slug:slug>/',  views.get_brands, name='brand_partial'),
    path('features_for_filter/<slug:slug>/',  views.get_feature_for_filter, name='features_for_filter'),
    
    path('status_of_compare_list/',  views.status_of_compare_list, name='status_of_compare_list'),
    path('compare_list/',  views.ShowCompareListView.as_view(), name='compare_list'),
    path('compare_table/',  views.compare_table, name='compare_table'),
    path('add_to_compare_list/',  views.add_to_compare_list, name='add_to_compare_list'),
    path('delete_from_compare_list/',  views.delete_from_compare_list, name='delete_from_compare_list'),
    
    path('category/',  views.category, name='category'),
    path('products_groups/<slug:slug>/',  views.products_groups, name='products_groups'),
    path('products_parent_group/<slug:slug>/',  views.products_parent_group, name='products_parent_group'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('discounts/', include('apps.discounts.urls', namespace='discounts')),
    path('payments/', include('apps.payments.urls', namespace='payments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    path('csf/', include('apps.comment_scoring_favorites.urls', namespace='csf')),
    path('search/', include('apps.search.urls', namespace='seach')),
    path('test_api/', include('apps.test_api.urls', namespace='test_api')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

shop/templates/products_app/partials/brands.html
{% load humanize %}
<div id="accordion">
    <div class="card" style="border: none; color:#868686;">
        <div class="card-header" style="padding:0 0 10px;">
            <a class="card-link" data-toggle="collapse" href="#collapseBrand"> 
                <button type="button" class="filter__title" data-collapse-trigger style="color:#000;"> 
                 برند <svg class="filter__arrow" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="32" height="32" viewBox="0 0 256 256" xml:space="preserve"> 
                <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit:10; fill:none; fill-rule:nonzero; opacity:1;" > 
                <path d="M 90 24.25 c 0 -0.896 -0.342 -1.792 -1.025 -2.475 c -1.366 -1.367 -3.583 -1.367 -4.949 0 L 45 60.8 L 85 100.8 c 1.366 1.367 3.583 1.367 4.949 0 c 1.366 -1.367 1.366 -3.583 0 -4.949 L 52 58 L 89 21.75 C 89.658 21.092 90 20.196 90 19.25 Z"></path>
                </g> 
                </svg> 
                </button> 
            </a>  
        </div>
        <div id="collapseBrand" class="collapse" data-parent="#accordion">
            <div class="card-body" style="padding: 0;">
                {% for brand in brands %}
                <label class="filter-list__item">
                    <span class="filter-list__input input-check">
                        <span class="input-check__body">
                            <input id="item-{{brand.id}}" name="brand" value="{{brand.id}}" type="checkbox" class="input-check__input" type="checkbox" > 
                            <span class="input-check__box"></span>
                            <svg class="input-check__icon" width="9px" height="7px">
                                <use xlink:href="images/sprite.svg#check-9x7"></use>
                            </svg>
                        </span>
                    </span>
                    <span class="filter-list__title">{{brand.brand_title}} </span>
                    <span class="filter-list__counter">{{brand.product_of_brands.all|length}}</span>
                </label>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

shop/templates/products_app/partials/cheapest_products.html
<div class="block block-products-carousel" data-layout="grid-5">
  <div class="container">
    {% include 'partials/products/root_group.html' with title='محصولات'   %}
    <div class="product-flexbox" style="">
      {% for product in products %}
        {% include 'partials/products/product_box.html' with type=1 %}
      {% endfor %}
    </div>
  </div>
</div>

shop/templates/products_app/partials/compare_table.html
{% if products %}
    <div class="container">
        <h2 style="text-align: center; color: green;">کالاهای انتخابی برای مقایسه</h2>
        <table class="table table-bordered">
            <tr style="background: #f1f1f1; text-align: center;">
                <th>ویژگی کالا/ کالا</th>
                {% for product in products %}
                    <th>
                        <i class="fa fa-times cursor-pointer product-remove" onclick="deleteFromCompareList({{product.id}})"></i>
                        {{product.product_name}}
                    </th>
                {% endfor %}
            </tr>

            {% for feature in features %}
                <tr>
                    <td style="font-size: 1.2rem; font-weight: 900; width: 25%;">{{feature}}</td>
                    {% for product in products %}
                        <td style="text-align: center;">
                            {% for item in product.product_feature.all %}
                                {% if item.feature == feature %}
                                    <span style="margin: 5px;">{{item.filter_value.value_title}}</span>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}

        </table>
    </div>
{% else %}
    <div class="container"></div>
        <h2 style="text-align: center; color: green; padding: 100px;">کالایی برای مقایسه وجود ندارد</h2>
{% endif %}

shop/templates/products_app/partials/features_filter.html
{% load humanize %}

<div id="accordion">
    {% for key, value in feature_dict.items %}
        {% if value %}
            <div class="card" style="border: none; color: #868686;">
                <div class="card-header" style="padding: 0 0 10px;">
                    <a class="card-link" data-toggle="collapse" href="#collapseOne{{ key.id }}">
                        <button type="button" class="filter__title" data-collapse-trigger style="color: #000;">
                            {{ key }}
                            <svg class="filter__arrow" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="32" height="32" viewBox="0 0 256 256" xml:space="preserve">
                                <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;">
                                    <path d="M 90 24.25 c 0 -0.896 -0.342 -1.792 -1.025 -2.475 c -1.366 -1.367 -3.583 -1.367 -4.949 0 L 45 60.8 L 85 100.8 c 1.366 1.367 3.583 1.367 4.949 0 c 1.366 -1.367 1.366 -3.583 0 -4.949 L 52 58 L 89 21.75 C 89.658 21.092 90 20.196 90 19.25 Z"></path>
                                </g>
                            </svg>
                        </button>
                    </a>
                </div>
                <div id="collapseOne{{ key.id }}" class="collapse" data-parent="#accordion">
                    <div class="card-body" style="padding: 0;">
                        {% for item in value %}
                            <label class="filter-list__item">
                                <span class="filter-list__input input-check">
                                    <span class="input-check__body">
                                        <input id="item-{{ item.id }}" name="feature" value="{{ item.id }}" type="checkbox" class="input-check__input">
                                        <span class="input-check__box"></span>
                                        <svg class="input-check__icon" width="9px" height="7px">
                                            <use xlink:href="images/sprite.svg#check-9x7"></use>
                                        </svg>
                                    </span>
                                </span>
                                <span class="filter-list__title">{{ item.value_title }}</span>
                            </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>

shop/templates/products_app/partials/last_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
      {% include 'partials/products/root_group.html' with title='جدید ترین محصولات ' %}
      <div class="product-flexbox" style="">
        {% for product in products %}
          {% include 'partials/products/product_box.html' with type=2 %}
        {% endfor %}
      </div>
    </div>
  </div>

shop/templates/products_app/partials/popular_product_groups.html
<div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">دسته های ضروری</h3>
            <div class="block-header__divider"></div>
        </div>
        <div class="block-categories__list">
            {% for group in product_groups %}
                <div class="block-categories__item category-card category-card--layout--compact">
                    <div class="category-card__body">
                        <div class="category-card__image">
                            <a href="{% url 'products:products_of_group' slug=group.slug %}">
                                <img src="{{media_url}}{{group.image_name}}" alt="">
                            </a>
                        </div>
                        <div class="category-card__content">
                            <div class="category-card__name">
                                <a href="{% url 'products:products_of_group' slug=group.slug %}">{{group.group_title}}</a>
                            </div>
                            <div class="category-card__products">{{group.products_of_groups.all|length}} محصول</div>
                        </div>
                    </div>
                    
                </div>
            {% endfor %}
            <a href="{% url "products:product_groups" %}">همه</a>
        </div>
    </div>
</div>

shop/templates/products_app/partials/product_groups.html
<ul class="filter-categories__list">
    {% for group in product_groups %}
    <li class="filter-categories__item filter-categories__item--parent">
        <a href="{% url "products:products_of_group" slug=group.slug %}">{{group.group_title}}</a>
        <div class="filter-categories__counter">{{group.products_of_groups.all|length}}</div>
    </li>
    {% endfor %}
</ul> 

shop/templates/products_app/partials/related_products.html
{% if related_products %}

<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
      {% include 'partials/products/root_group.html' with title='محصولات مرتبط' %}
      <div class="product-flexbox" style="">
        {% for product in related_products %}
          {% include 'partials/products/product_box.html' with type=1 %}
        {% endfor %}
      </div>
    </div>
  </div>

  {% endif %}

shop/templates/products_app/partials/sorte_price.html
<div class="view-options__control">
    <label for="">مرتب‌سازی بر اساس</label>
    <div>
      <select class="form-control form-control-sm" name="" id="select_sort" onchange="select_sort()">
            {% if sort_type == '0' %}
              <option value="0" selected>پیش فرض</option>
              <option value="1">قیمت از کم به زیاد</option>
              <option value="2">قیمت از زیاد به کم</option>

            {% elif sort_type == '1' %}
              <option value="0">پیش فرض</option>
              <option value="1" selected>قیمت از کم به زیاد</option>
              <option value="2">قیمت از زیاد به کم</option>
                
            {% elif sort_type == '2' %}
              <option value="0">پیش فرض</option>
              <option value="1">قیمت از کم به زیاد</option>
              <option value="2" selected>قیمت از زیاد به کم</option>
              
            {% endif %}
      </select>
    </div>
</div>



  {% comment %} <div class="view-options__control">  
    <label for="select_sort">مرتب‌سازی بر اساس</label>  
    <div>  
        <select class="form-control form-control-sm" id="select_sort" onchange="select_sort()">  
            <option value="0" {% if sort_type == '0' %} selected {% endif %}>پیش فرض</option>  
            <option value="1" {% if sort_type == '1' %} selected {% endif %}>قیمت از کم به زیاد</option>  
            <option value="2" {% if sort_type == '2' %} selected {% endif %}>قیمت از زیاد به کم</option>  
        </select>  
    </div>  
</div>   {% endcomment %}